import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { poppins } from "../frontend/assets/fonts";
import SessionGuard from "@/frontend/auth/SessionGuard";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CHRIS",
  description: "Generated by create next app",
  icons: {
    icon: "/images/[DEPED] ELMS Logo.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased`}
      >
        <SessionGuard />
        {children}
      </body>
    </html>
  );
}
